language: node_js
dist: xenial

node_js:
  - '12'

cache:
  yarn: true

notifications:
  email: false

before_install:
  - curl https://yarnpkg.com/install.sh -sSfL | bash -s --
  - export PATH="${HOME}/.yarn/bin:${PATH}"

script:
  - yarn lint
  - yarn dist
  - yarn test
